kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.crazycow.ninja/test-app
      tags: 1
      registry: registry.crazycow.ninja
      username:
        from_secret: registry-user
      password:
        from_secret: registry-password
    when:
      branch:
        - master
      event:
        - push
